name: ci

on:
  push:
    branches: [master]

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 7.3, 7.2]
    env:
      LATEST_PHP: 7.4
      IMAGE_NAME: t3easy/php
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push latest image
      uses: docker/build-push-action@v2
      if: ${{ matrix.php == env.LATEST_PHP }}
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          PHP_VERSION=${{ matrix.php }}
          TARGET_ENVIRONMENT=production
        tags: |
          ${{ env.IMAGE_NAME }}
          ghcr.io/${{ env.IMAGE_NAME }}
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
        cache-from: type=local,src=/tmp/.buildx-cache

    - name: Build and push production images
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          PHP_VERSION=${{ matrix.php }}
          TARGET_ENVIRONMENT=production
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}-production
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}-production
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
        cache-from: type=local,src=/tmp/.buildx-cache

    - name: Build and push development images
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          PHP_VERSION=${{ matrix.php }}
          TARGET_ENVIRONMENT=development
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}-development
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}-development
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
        cache-from: type=local,src=/tmp/.buildx-cache
