name: Build and push Docker images

on:
  schedule:
  - cron: '42 4 * * *'
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        include:
        - php: "8.2"
          php-ext-dir: /usr/local/lib/php/extensions/no-debug-non-zts-20220829
          alpine: "3.18"
          xdebug: "3.2.1"
        - php: "8.1"
          php-ext-dir: /usr/local/lib/php/extensions/no-debug-non-zts-20210902
          alpine: "3.18"
          xdebug: "3.2.1"
        - php: "8.0"
          php-ext-dir: /usr/local/lib/php/extensions/no-debug-non-zts-20200930
          alpine: "3.16"
          xdebug: "3.2.1"
        - php: "7.4"
          php-ext-dir: /usr/local/lib/php/extensions/no-debug-non-zts-20190902
          alpine: "3.16"
          xdebug: "3.1.6"

    env:
      LATEST_PHP: "8.2"
      IMAGE_NAME: t3easy/php
      PLATFORMS: linux/amd64,linux/arm64

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push latest image
      uses: docker/build-push-action@v2
      if: ${{ matrix.php == env.LATEST_PHP }}
      with:
        push: ${{ github.event_name != 'pull_request' }}
        platforms: ${{ env.PLATFORMS }}
        build-args: |
          PHP_VERSION=${{ matrix.php }}
          PHP_EXT_DIR=${{ matrix.php-ext-dir }}
          XDEBUG_VERSION=${{ matrix.xdebug }}
          TARGET_ENVIRONMENT=production
        tags: |
          ${{ env.IMAGE_NAME }}
          ghcr.io/${{ env.IMAGE_NAME }}
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}-production
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}-production
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Build and push production images
      uses: docker/build-push-action@v2
      if: ${{ matrix.php != env.LATEST_PHP }}
      with:
        push: ${{ github.event_name != 'pull_request' }}
        platforms: ${{ env.PLATFORMS }}
        build-args: |
          ALPINE_VERSION=${{ matrix.alpine }}
          PHP_VERSION=${{ matrix.php }}
          PHP_EXT_DIR=${{ matrix.php-ext-dir }}
          XDEBUG_VERSION=${{ matrix.xdebug }}
          TARGET_ENVIRONMENT=production
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}-production
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}-production
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Build and push development images
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        platforms: ${{ env.PLATFORMS }}
        build-args: |
          ALPINE_VERSION=${{ matrix.alpine }}
          PHP_VERSION=${{ matrix.php }}
          PHP_EXT_DIR=${{ matrix.php-ext-dir }}
          XDEBUG_VERSION=${{ matrix.xdebug }}
          TARGET_ENVIRONMENT=development
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.php }}-development
          ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.php }}-development
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
