name: ci

on:
  push:
    branches: master

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 7.3, 7.2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push production images
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          PHP_VERSION=${{ matrix.php }}
          TARGET_ENVIRONMENT=production
        tags: |
          t3easy/php:${{ matrix.php }}
          t3easy/php:${{ matrix.php }}-production
          ghcr.io/${{ github.repository_owner }}/php:${{ matrix.php }}
          ghcr.io/${{ github.repository_owner }}/php:${{ matrix.php }}-production

    - name: Build and push development images
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          PHP_VERSION=${{ matrix.php }}
          TARGET_ENVIRONMENT=development
        tags: |
          t3easy/php:${{ matrix.php }}-development
          ghcr.io/${{ github.repository_owner }}/php:${{ matrix.php }}-development
